language: node_js
node_js:
- 8.4.0
script: npm start & node ./server/index.js & npm run test
env:
  secure: c3kFFae1uztRzi4cjGxr+0HBo8ttvHtKaM+VIenkQ7OPzro4yses7br4xhifjCNp4y+nAXFnxHtwLfVvutVUj3jSWtD15Kl154CcabFUCbD66ZLDd6sVSQkKYllYUpaoYvl1UbSiSjP13hqXngM0eudM0EU7ImhzMbsJMpAeAWtpVCT2tNi3bIz8i/dRNNYAlIbHKmY+1EnN45ZNaxLX0UZo1wrJ2mp9j+GSQ/qaMFMzIIYB5nqYD0npT9jKefRach3z0jK2Zztd7f+S7b7+hzV4HYI7z9lGFLAE/IAC6HyBDnNU3mhDFHWCvVO1dy8CfcErhVj5NGGqCeQqVq01OC1giFRaAtBQsTOp9O7B1LQn3FB8J/TdSScVzI73VJlerXVC6wRK9F1/jxMs1aFmk723i+t2/Bq9R+W33EQ8T40J3VqdhnVYqsYjGQooTAkvQ6TzXjszLPUcIEMIgcULI2xxF6LcJzlbDh7dH6e20X0LKMTdFzt//Daqx1jP5heewWzjJt016XHp549Zco1FRvzZ4jZKRpriimORngr+vQDeEswvVSvM2sDEs4TkOqPAvSAm1DjDVrJyM/BG9DKKt3qHdrmDkb+iP6CPxD1CzOZMzeS0gDjRSVS6PkcWNlKz7m4uHUQrbgxMdAF4/bE4sws3szImF9rpOq1dAwcXpsM=
