language: node_js
node_js:
- 8.4.0
script: npm start & node ./server/index.js & npm run test
env:
  global:
    - DB_URL: postgres://abc:d0ef@hi-j.compute-1.amazonaws.com:5432/dedjj9hcdfiie5
    - secure: "FOQUnYjmrkgK1HMvtn4wFbGvCB1MW6zF7KOoCCxtqZfPnsoK/cRN1fDDl2swgScLwROCX1uCgLnDK8r3LYZvmLQ6LIBXtlOVPmAC0yio7RyeTqAy2h1AtK6cT6zFoUZcxY6JK6siUOvPqqikp3vpOFi5SODmfGaJ3HM7c5VZHp1Qo3sies4zM6xRcihr6zM0JF/uDYFjIvuUJuUh39ATUTAwhXypAHPZGmq27+FVJlXJiDqgkLDb0oOzxjzfcW1MmZEoUNmQdLr2Er+4ROyL5xctbxlrHnBOFn6kZEjX8JmaSvRwrskYOnSuK2XYTRflqwZ2EfYq6QbIyyJdJ8JGNis95ej0veEy+eR8Zfij6eEwzwYpjuiLNPtTm3zCi7NNnwWxTqkdWnwjcGpzXN+xmjpuYqbXveuSyN9Bvw5DQU92uPh51RNGgLyKcwaZmfllKn0MmgFM90Qx9AU9NwSW2JJnEM8geWl6AL5H1Hjzwebgo0+E7n+/RrS5rSVSN14Iz6jPJAfGXJDH6TwT+lTRyFBaHuh/CAHvGPLklEWDRO6quMN+K2RU8D7CsXNLloF3zbLeo9K9LhSdV10pxXPmoZdDDfmAEtgnIVFwevADtWcA6cqrLtRhQpXcUI+WZMXYq/tKnlOI7Kj6LLVolWWQfnCOwYo6+knun6QutyvXmW0="
