language: node_js
node_js:
- 8.4.0
script: npm start & node ./server/index.js & npm run test

env:
  - DB=postgres
  - TEST=postgres://abc:d0ef@hi-j.compute-1.amazonaws.com:5432/dedjj9hcdfiie5
  - TEST_ENCODED=postgres%3A%2F%2Fabc%3Ad0ef%40hi-j.compute-1.amazonaws.com%3A5432%2Fdedjj9hcdfiie5
  - TEST_QUOTE1='a'
  - TEST_QUOTE2="a"
  - TEST_BASE=hello
